version = '0.0.1'

[[files."CHANGELOG.rst"]]
search = """
`Unreleased`_
*************
"""
replace = """
`Unreleased`_
*************

`{{new_version}}`_ - {{utcnow | strftime('%Y-%m-%d')}}
*******************************
"""

[[files."CHANGELOG.rst"]]
search = """
.. _`Unreleased`: https://github.com/labpositiva/cookiecutter-docker/compare/{{old_version}}...HEAD
"""
replace = """
.. _`Unreleased`: https://github.com/labpositiva/cookiecutter-docker/compare/{{new_version}}...HEAD
.. _`{{new_version}}`: https://github.com/labpositiva/cookiecutter-docker/compare/{{old_version}}...{{new_version}}
"""
